package com.young.db.dao;

import com.young.db.entity.YoungComment;
import com.young.db.entity.YoungCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungCommentMapper {
    long countByExample(YoungCommentExample example);

    int deleteByExample(YoungCommentExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungComment record);

    int insertSelective(YoungComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungComment selectOneByExample(YoungCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungComment selectOneByExampleSelective(@Param("example") YoungCommentExample example, @Param("selective") YoungComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungComment> selectByExampleSelective(@Param("example") YoungCommentExample example, @Param("selective") YoungComment.Column ... selective);

    List<YoungComment> selectByExample(YoungCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungComment.Column ... selective);

    YoungComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungComment record, @Param("example") YoungCommentExample example);

    int updateByExample(@Param("record") YoungComment record, @Param("example") YoungCommentExample example);

    int updateByPrimaryKeySelective(YoungComment record);

    int updateByPrimaryKey(YoungComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}