package com.young.db.dao;

import com.young.db.entity.YoungCart;
import com.young.db.entity.YoungCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungCartMapper {
    long countByExample(YoungCartExample example);

    int deleteByExample(YoungCartExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungCart record);

    int insertSelective(YoungCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCart selectOneByExample(YoungCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCart selectOneByExampleSelective(@Param("example") YoungCartExample example, @Param("selective") YoungCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungCart> selectByExampleSelective(@Param("example") YoungCartExample example, @Param("selective") YoungCart.Column ... selective);

    List<YoungCart> selectByExample(YoungCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungCart.Column ... selective);

    YoungCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungCart record, @Param("example") YoungCartExample example);

    int updateByExample(@Param("record") YoungCart record, @Param("example") YoungCartExample example);

    int updateByPrimaryKeySelective(YoungCart record);

    int updateByPrimaryKey(YoungCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}