package com.young.db.dao;

import com.young.db.entity.YoungKeyword;
import com.young.db.entity.YoungKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungKeywordMapper {
    long countByExample(YoungKeywordExample example);

    int deleteByExample(YoungKeywordExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungKeyword record);

    int insertSelective(YoungKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungKeyword selectOneByExample(YoungKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungKeyword selectOneByExampleSelective(@Param("example") YoungKeywordExample example, @Param("selective") YoungKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungKeyword> selectByExampleSelective(@Param("example") YoungKeywordExample example, @Param("selective") YoungKeyword.Column ... selective);

    List<YoungKeyword> selectByExample(YoungKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungKeyword.Column ... selective);

    YoungKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungKeyword record, @Param("example") YoungKeywordExample example);

    int updateByExample(@Param("record") YoungKeyword record, @Param("example") YoungKeywordExample example);

    int updateByPrimaryKeySelective(YoungKeyword record);

    int updateByPrimaryKey(YoungKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}