package com.young.db.dao;

import com.young.db.entity.YoungSystem;
import com.young.db.entity.YoungSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungSystemMapper {
    long countByExample(YoungSystemExample example);

    int deleteByExample(YoungSystemExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungSystem record);

    int insertSelective(YoungSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSystem selectOneByExample(YoungSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSystem selectOneByExampleSelective(@Param("example") YoungSystemExample example, @Param("selective") YoungSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungSystem> selectByExampleSelective(@Param("example") YoungSystemExample example, @Param("selective") YoungSystem.Column ... selective);

    List<YoungSystem> selectByExample(YoungSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungSystem.Column ... selective);

    YoungSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungSystem record, @Param("example") YoungSystemExample example);

    int updateByExample(@Param("record") YoungSystem record, @Param("example") YoungSystemExample example);

    int updateByPrimaryKeySelective(YoungSystem record);

    int updateByPrimaryKey(YoungSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}