package com.young.db.dao;

import com.young.db.entity.YoungIssue;
import com.young.db.entity.YoungIssueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungIssueMapper {
    long countByExample(YoungIssueExample example);

    int deleteByExample(YoungIssueExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungIssue record);

    int insertSelective(YoungIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungIssue selectOneByExample(YoungIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungIssue selectOneByExampleSelective(@Param("example") YoungIssueExample example, @Param("selective") YoungIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungIssue> selectByExampleSelective(@Param("example") YoungIssueExample example, @Param("selective") YoungIssue.Column ... selective);

    List<YoungIssue> selectByExample(YoungIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungIssue.Column ... selective);

    YoungIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungIssue record, @Param("example") YoungIssueExample example);

    int updateByExample(@Param("record") YoungIssue record, @Param("example") YoungIssueExample example);

    int updateByPrimaryKeySelective(YoungIssue record);

    int updateByPrimaryKey(YoungIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}