package com.young.db.dao;

import com.young.db.entity.YoungCouponUser;
import com.young.db.entity.YoungCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungCouponUserMapper {
    long countByExample(YoungCouponUserExample example);

    int deleteByExample(YoungCouponUserExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungCouponUser record);

    int insertSelective(YoungCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCouponUser selectOneByExample(YoungCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCouponUser selectOneByExampleSelective(@Param("example") YoungCouponUserExample example, @Param("selective") YoungCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungCouponUser> selectByExampleSelective(@Param("example") YoungCouponUserExample example, @Param("selective") YoungCouponUser.Column ... selective);

    List<YoungCouponUser> selectByExample(YoungCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungCouponUser.Column ... selective);

    YoungCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungCouponUser record, @Param("example") YoungCouponUserExample example);

    int updateByExample(@Param("record") YoungCouponUser record, @Param("example") YoungCouponUserExample example);

    int updateByPrimaryKeySelective(YoungCouponUser record);

    int updateByPrimaryKey(YoungCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}