package com.young.db.dao;

import com.young.db.entity.YoungAd;
import com.young.db.entity.YoungAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungAdMapper {
    long countByExample(YoungAdExample example);

    int deleteByExample(YoungAdExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungAd record);

    int insertSelective(YoungAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAd selectOneByExample(YoungAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAd selectOneByExampleSelective(@Param("example") YoungAdExample example, @Param("selective") YoungAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungAd> selectByExampleSelective(@Param("example") YoungAdExample example, @Param("selective") YoungAd.Column ... selective);

    List<YoungAd> selectByExample(YoungAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungAd.Column ... selective);

    YoungAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungAd record, @Param("example") YoungAdExample example);

    int updateByExample(@Param("record") YoungAd record, @Param("example") YoungAdExample example);

    int updateByPrimaryKeySelective(YoungAd record);

    int updateByPrimaryKey(YoungAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}