package com.young.db.dao;

import com.young.db.entity.YoungGoodsAttribute;
import com.young.db.entity.YoungGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungGoodsAttributeMapper {
    long countByExample(YoungGoodsAttributeExample example);

    int deleteByExample(YoungGoodsAttributeExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungGoodsAttribute record);

    int insertSelective(YoungGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoodsAttribute selectOneByExample(YoungGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoodsAttribute selectOneByExampleSelective(@Param("example") YoungGoodsAttributeExample example, @Param("selective") YoungGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungGoodsAttribute> selectByExampleSelective(@Param("example") YoungGoodsAttributeExample example, @Param("selective") YoungGoodsAttribute.Column ... selective);

    List<YoungGoodsAttribute> selectByExample(YoungGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungGoodsAttribute.Column ... selective);

    YoungGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungGoodsAttribute record, @Param("example") YoungGoodsAttributeExample example);

    int updateByExample(@Param("record") YoungGoodsAttribute record, @Param("example") YoungGoodsAttributeExample example);

    int updateByPrimaryKeySelective(YoungGoodsAttribute record);

    int updateByPrimaryKey(YoungGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}