package com.young.db.dao;

import com.young.db.entity.YoungRole;
import com.young.db.entity.YoungRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungRoleMapper {
    long countByExample(YoungRoleExample example);

    int deleteByExample(YoungRoleExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungRole record);

    int insertSelective(YoungRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRole selectOneByExample(YoungRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRole selectOneByExampleSelective(@Param("example") YoungRoleExample example, @Param("selective") YoungRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungRole> selectByExampleSelective(@Param("example") YoungRoleExample example, @Param("selective") YoungRole.Column ... selective);

    List<YoungRole> selectByExample(YoungRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungRole.Column ... selective);

    YoungRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungRole record, @Param("example") YoungRoleExample example);

    int updateByExample(@Param("record") YoungRole record, @Param("example") YoungRoleExample example);

    int updateByPrimaryKeySelective(YoungRole record);

    int updateByPrimaryKey(YoungRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}