package com.young.db.dao;

import com.young.db.entity.YoungStorage;
import com.young.db.entity.YoungStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungStorageMapper {
    long countByExample(YoungStorageExample example);

    int deleteByExample(YoungStorageExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungStorage record);

    int insertSelective(YoungStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungStorage selectOneByExample(YoungStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungStorage selectOneByExampleSelective(@Param("example") YoungStorageExample example, @Param("selective") YoungStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungStorage> selectByExampleSelective(@Param("example") YoungStorageExample example, @Param("selective") YoungStorage.Column ... selective);

    List<YoungStorage> selectByExample(YoungStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungStorage.Column ... selective);

    YoungStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungStorage record, @Param("example") YoungStorageExample example);

    int updateByExample(@Param("record") YoungStorage record, @Param("example") YoungStorageExample example);

    int updateByPrimaryKeySelective(YoungStorage record);

    int updateByPrimaryKey(YoungStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}