package com.young.db.dao;

import com.young.db.entity.YoungAccountTrace;
import com.young.db.entity.YoungAccountTraceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungAccountTraceMapper {
    long countByExample(YoungAccountTraceExample example);

    int deleteByExample(YoungAccountTraceExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungAccountTrace record);

    int insertSelective(YoungAccountTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAccountTrace selectOneByExample(YoungAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAccountTrace selectOneByExampleSelective(@Param("example") YoungAccountTraceExample example, @Param("selective") YoungAccountTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungAccountTrace> selectByExampleSelective(@Param("example") YoungAccountTraceExample example, @Param("selective") YoungAccountTrace.Column ... selective);

    List<YoungAccountTrace> selectByExample(YoungAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAccountTrace selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungAccountTrace.Column ... selective);

    YoungAccountTrace selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") YoungAccountTrace record, @Param("example") YoungAccountTraceExample example);

    int updateByExample(@Param("record") YoungAccountTrace record, @Param("example") YoungAccountTraceExample example);

    int updateByPrimaryKeySelective(YoungAccountTrace record);

    int updateByPrimaryKey(YoungAccountTrace record);
}