package com.young.db.dao;

import com.young.db.entity.YoungUserFormid;
import com.young.db.entity.YoungUserFormidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungUserFormidMapper {
    long countByExample(YoungUserFormidExample example);

    int deleteByExample(YoungUserFormidExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungUserFormid record);

    int insertSelective(YoungUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungUserFormid selectOneByExample(YoungUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungUserFormid selectOneByExampleSelective(@Param("example") YoungUserFormidExample example, @Param("selective") YoungUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungUserFormid> selectByExampleSelective(@Param("example") YoungUserFormidExample example, @Param("selective") YoungUserFormid.Column ... selective);

    List<YoungUserFormid> selectByExample(YoungUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungUserFormid.Column ... selective);

    YoungUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungUserFormid record, @Param("example") YoungUserFormidExample example);

    int updateByExample(@Param("record") YoungUserFormid record, @Param("example") YoungUserFormidExample example);

    int updateByPrimaryKeySelective(YoungUserFormid record);

    int updateByPrimaryKey(YoungUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}