package com.young.db.dao;

import com.young.db.entity.YoungDelPicture;
import com.young.db.entity.YoungDelPictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungDelPictureMapper {
    long countByExample(YoungDelPictureExample example);

    int deleteByExample(YoungDelPictureExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungDelPicture record);

    int insertSelective(YoungDelPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungDelPicture selectOneByExample(YoungDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungDelPicture selectOneByExampleSelective(@Param("example") YoungDelPictureExample example, @Param("selective") YoungDelPicture.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungDelPicture> selectByExampleSelective(@Param("example") YoungDelPictureExample example, @Param("selective") YoungDelPicture.Column ... selective);

    List<YoungDelPicture> selectByExample(YoungDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungDelPicture selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungDelPicture.Column ... selective);

    YoungDelPicture selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") YoungDelPicture record, @Param("example") YoungDelPictureExample example);

    int updateByExample(@Param("record") YoungDelPicture record, @Param("example") YoungDelPictureExample example);

    int updateByPrimaryKeySelective(YoungDelPicture record);

    int updateByPrimaryKey(YoungDelPicture record);
}