package com.young.db.dao;

import com.young.db.entity.YoungRegion;
import com.young.db.entity.YoungRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungRegionMapper {
    long countByExample(YoungRegionExample example);

    int deleteByExample(YoungRegionExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungRegion record);

    int insertSelective(YoungRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRegion selectOneByExample(YoungRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRegion selectOneByExampleSelective(@Param("example") YoungRegionExample example, @Param("selective") YoungRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungRegion> selectByExampleSelective(@Param("example") YoungRegionExample example, @Param("selective") YoungRegion.Column ... selective);

    List<YoungRegion> selectByExample(YoungRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungRegion.Column ... selective);

    YoungRegion selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") YoungRegion record, @Param("example") YoungRegionExample example);

    int updateByExample(@Param("record") YoungRegion record, @Param("example") YoungRegionExample example);

    int updateByPrimaryKeySelective(YoungRegion record);

    int updateByPrimaryKey(YoungRegion record);
}