package com.young.db.dao;

import com.young.db.entity.YoungFeedback;
import com.young.db.entity.YoungFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungFeedbackMapper {
    long countByExample(YoungFeedbackExample example);

    int deleteByExample(YoungFeedbackExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungFeedback record);

    int insertSelective(YoungFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungFeedback selectOneByExample(YoungFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungFeedback selectOneByExampleSelective(@Param("example") YoungFeedbackExample example, @Param("selective") YoungFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungFeedback> selectByExampleSelective(@Param("example") YoungFeedbackExample example, @Param("selective") YoungFeedback.Column ... selective);

    List<YoungFeedback> selectByExample(YoungFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungFeedback.Column ... selective);

    YoungFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungFeedback record, @Param("example") YoungFeedbackExample example);

    int updateByExample(@Param("record") YoungFeedback record, @Param("example") YoungFeedbackExample example);

    int updateByPrimaryKeySelective(YoungFeedback record);

    int updateByPrimaryKey(YoungFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}