package com.young.db.dao;

import com.young.db.entity.YoungSeckillPromotion;
import com.young.db.entity.YoungSeckillPromotionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface YoungSeckillPromotionMapper {
    long countByExample(YoungSeckillPromotionExample example);

    int deleteByExample(YoungSeckillPromotionExample example);

    int deleteByPrimaryKey(Long id);

    int insert(YoungSeckillPromotion record);

    int insertSelective(YoungSeckillPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_seckill_promotion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSeckillPromotion selectOneByExample(YoungSeckillPromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_seckill_promotion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSeckillPromotion selectOneByExampleSelective(@Param("example") YoungSeckillPromotionExample example, @Param("selective") YoungSeckillPromotion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_seckill_promotion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungSeckillPromotion> selectByExampleSelective(@Param("example") YoungSeckillPromotionExample example, @Param("selective") YoungSeckillPromotion.Column ... selective);

    List<YoungSeckillPromotion> selectByExample(YoungSeckillPromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_seckill_promotion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSeckillPromotion selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") YoungSeckillPromotion.Column ... selective);

    YoungSeckillPromotion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_seckill_promotion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSeckillPromotion selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungSeckillPromotion record, @Param("example") YoungSeckillPromotionExample example);

    int updateByExample(@Param("record") YoungSeckillPromotion record, @Param("example") YoungSeckillPromotionExample example);

    int updateByPrimaryKeySelective(YoungSeckillPromotion record);

    int updateByPrimaryKey(YoungSeckillPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_seckill_promotion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungSeckillPromotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_seckill_promotion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long id);
}
