package com.young.db.dao;

import com.young.db.entity.YoungOrderGoods;
import com.young.db.entity.YoungOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungOrderGoodsMapper {
    long countByExample(YoungOrderGoodsExample example);

    int deleteByExample(YoungOrderGoodsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungOrderGoods record);

    int insertSelective(YoungOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungOrderGoods selectOneByExample(YoungOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungOrderGoods selectOneByExampleSelective(@Param("example") YoungOrderGoodsExample example, @Param("selective") YoungOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungOrderGoods> selectByExampleSelective(@Param("example") YoungOrderGoodsExample example, @Param("selective") YoungOrderGoods.Column ... selective);

    List<YoungOrderGoods> selectByExample(YoungOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungOrderGoods.Column ... selective);

    YoungOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungOrderGoods record, @Param("example") YoungOrderGoodsExample example);

    int updateByExample(@Param("record") YoungOrderGoods record, @Param("example") YoungOrderGoodsExample example);

    int updateByPrimaryKeySelective(YoungOrderGoods record);

    int updateByPrimaryKey(YoungOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}