package com.young.db.dao;

import com.young.db.entity.YoungCollect;
import com.young.db.entity.YoungCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungCollectMapper {
    long countByExample(YoungCollectExample example);

    int deleteByExample(YoungCollectExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungCollect record);

    int insertSelective(YoungCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCollect selectOneByExample(YoungCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCollect selectOneByExampleSelective(@Param("example") YoungCollectExample example, @Param("selective") YoungCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungCollect> selectByExampleSelective(@Param("example") YoungCollectExample example, @Param("selective") YoungCollect.Column ... selective);

    List<YoungCollect> selectByExample(YoungCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungCollect.Column ... selective);

    YoungCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungCollect record, @Param("example") YoungCollectExample example);

    int updateByExample(@Param("record") YoungCollect record, @Param("example") YoungCollectExample example);

    int updateByPrimaryKeySelective(YoungCollect record);

    int updateByPrimaryKey(YoungCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}