package com.young.db.dao;

import com.young.db.entity.YoungSearchHistory;
import com.young.db.entity.YoungSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungSearchHistoryMapper {
    long countByExample(YoungSearchHistoryExample example);

    int deleteByExample(YoungSearchHistoryExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungSearchHistory record);

    int insertSelective(YoungSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSearchHistory selectOneByExample(YoungSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSearchHistory selectOneByExampleSelective(@Param("example") YoungSearchHistoryExample example, @Param("selective") YoungSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungSearchHistory> selectByExampleSelective(@Param("example") YoungSearchHistoryExample example, @Param("selective") YoungSearchHistory.Column ... selective);

    List<YoungSearchHistory> selectByExample(YoungSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungSearchHistory.Column ... selective);

    YoungSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungSearchHistory record, @Param("example") YoungSearchHistoryExample example);

    int updateByExample(@Param("record") YoungSearchHistory record, @Param("example") YoungSearchHistoryExample example);

    int updateByPrimaryKeySelective(YoungSearchHistory record);

    int updateByPrimaryKey(YoungSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}