package com.young.db.dao;

import com.young.db.entity.YoungOrder;
import com.young.db.entity.YoungOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungOrderMapper {
    long countByExample(YoungOrderExample example);

    int deleteByExample(YoungOrderExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungOrder record);

    int insertSelective(YoungOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungOrder selectOneByExample(YoungOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungOrder selectOneByExampleSelective(@Param("example") YoungOrderExample example, @Param("selective") YoungOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungOrder> selectByExampleSelective(@Param("example") YoungOrderExample example, @Param("selective") YoungOrder.Column ... selective);

    List<YoungOrder> selectByExample(YoungOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungOrder.Column ... selective);

    YoungOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungOrder record, @Param("example") YoungOrderExample example);

    int updateByExample(@Param("record") YoungOrder record, @Param("example") YoungOrderExample example);

    int updateByPrimaryKeySelective(YoungOrder record);

    int updateByPrimaryKey(YoungOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}