package com.young.db.dao;

import com.young.db.entity.YoungUser;
import com.young.db.entity.YoungUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungUserMapper {
    long countByExample(YoungUserExample example);

    int deleteByExample(YoungUserExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungUser record);

    int insertSelective(YoungUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungUser selectOneByExample(YoungUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungUser selectOneByExampleSelective(@Param("example") YoungUserExample example, @Param("selective") YoungUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungUser> selectByExampleSelective(@Param("example") YoungUserExample example, @Param("selective") YoungUser.Column ... selective);

    List<YoungUser> selectByExample(YoungUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungUser.Column ... selective);

    YoungUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungUser record, @Param("example") YoungUserExample example);

    int updateByExample(@Param("record") YoungUser record, @Param("example") YoungUserExample example);

    int updateByPrimaryKeySelective(YoungUser record);

    int updateByPrimaryKey(YoungUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}