package com.young.db.dao;

import com.young.db.entity.YoungGoods;
import com.young.db.entity.YoungGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungGoodsMapper {
    long countByExample(YoungGoodsExample example);

    int deleteByExample(YoungGoodsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungGoods record);

    int insertSelective(YoungGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoods selectOneByExample(YoungGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoods selectOneByExampleSelective(@Param("example") YoungGoodsExample example, @Param("selective") YoungGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoods selectOneByExampleWithBLOBs(YoungGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungGoods> selectByExampleSelective(@Param("example") YoungGoodsExample example, @Param("selective") YoungGoods.Column ... selective);

    List<YoungGoods> selectByExampleWithBLOBs(YoungGoodsExample example);

    List<YoungGoods> selectByExample(YoungGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungGoods.Column ... selective);

    YoungGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungGoods record, @Param("example") YoungGoodsExample example);

    int updateByExampleWithBLOBs(@Param("record") YoungGoods record, @Param("example") YoungGoodsExample example);

    int updateByExample(@Param("record") YoungGoods record, @Param("example") YoungGoodsExample example);

    int updateByPrimaryKeySelective(YoungGoods record);

    int updateByPrimaryKeyWithBLOBs(YoungGoods record);

    int updateByPrimaryKey(YoungGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}