package com.young.db.dao;

import com.young.db.entity.YoungRolePermission;
import com.young.db.entity.YoungRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungRolePermissionMapper {
    long countByExample(YoungRolePermissionExample example);

    int deleteByExample(YoungRolePermissionExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungRolePermission record);

    int insertSelective(YoungRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRolePermission selectOneByExample(YoungRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRolePermission selectOneByExampleSelective(@Param("example") YoungRolePermissionExample example, @Param("selective") YoungRolePermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungRolePermission> selectByExampleSelective(@Param("example") YoungRolePermissionExample example, @Param("selective") YoungRolePermission.Column ... selective);

    List<YoungRolePermission> selectByExample(YoungRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungRolePermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungRolePermission.Column ... selective);

    YoungRolePermission selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") YoungRolePermission record, @Param("example") YoungRolePermissionExample example);

    int updateByExample(@Param("record") YoungRolePermission record, @Param("example") YoungRolePermissionExample example);

    int updateByPrimaryKeySelective(YoungRolePermission record);

    int updateByPrimaryKey(YoungRolePermission record);
}