package com.young.db.dao;

import com.young.db.entity.YoungCoupon;
import com.young.db.entity.YoungCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungCouponMapper {
    long countByExample(YoungCouponExample example);

    int deleteByExample(YoungCouponExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungCoupon record);

    int insertSelective(YoungCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCoupon selectOneByExample(YoungCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCoupon selectOneByExampleSelective(@Param("example") YoungCouponExample example, @Param("selective") YoungCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungCoupon> selectByExampleSelective(@Param("example") YoungCouponExample example, @Param("selective") YoungCoupon.Column ... selective);

    List<YoungCoupon> selectByExample(YoungCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungCoupon.Column ... selective);

    YoungCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungCoupon record, @Param("example") YoungCouponExample example);

    int updateByExample(@Param("record") YoungCoupon record, @Param("example") YoungCouponExample example);

    int updateByPrimaryKeySelective(YoungCoupon record);

    int updateByPrimaryKey(YoungCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_coupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}