package com.young.db.dao;

import com.young.db.entity.YoungCategory;
import com.young.db.entity.YoungCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungCategoryMapper {
    long countByExample(YoungCategoryExample example);

    int deleteByExample(YoungCategoryExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungCategory record);

    int insertSelective(YoungCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCategory selectOneByExample(YoungCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCategory selectOneByExampleSelective(@Param("example") YoungCategoryExample example, @Param("selective") YoungCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungCategory> selectByExampleSelective(@Param("example") YoungCategoryExample example, @Param("selective") YoungCategory.Column ... selective);

    List<YoungCategory> selectByExample(YoungCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungCategory.Column ... selective);

    YoungCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungCategory record, @Param("example") YoungCategoryExample example);

    int updateByExample(@Param("record") YoungCategory record, @Param("example") YoungCategoryExample example);

    int updateByPrimaryKeySelective(YoungCategory record);

    int updateByPrimaryKey(YoungCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}