package com.young.db.dao;

import com.young.db.entity.YoungGoodsProduct;
import com.young.db.entity.YoungGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungGoodsProductMapper {
    long countByExample(YoungGoodsProductExample example);

    int deleteByExample(YoungGoodsProductExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungGoodsProduct record);

    int insertSelective(YoungGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoodsProduct selectOneByExample(YoungGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoodsProduct selectOneByExampleSelective(@Param("example") YoungGoodsProductExample example, @Param("selective") YoungGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungGoodsProduct> selectByExampleSelective(@Param("example") YoungGoodsProductExample example, @Param("selective") YoungGoodsProduct.Column ... selective);

    List<YoungGoodsProduct> selectByExample(YoungGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungGoodsProduct.Column ... selective);

    YoungGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungGoodsProduct record, @Param("example") YoungGoodsProductExample example);

    int updateByExample(@Param("record") YoungGoodsProduct record, @Param("example") YoungGoodsProductExample example);

    int updateByPrimaryKeySelective(YoungGoodsProduct record);

    int updateByPrimaryKey(YoungGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}