package com.young.db.dao;

import com.young.db.entity.YoungPermission;
import com.young.db.entity.YoungPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungPermissionMapper {
    long countByExample(YoungPermissionExample example);

    int deleteByExample(YoungPermissionExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungPermission record);

    int insertSelective(YoungPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungPermission selectOneByExample(YoungPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungPermission selectOneByExampleSelective(@Param("example") YoungPermissionExample example, @Param("selective") YoungPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungPermission> selectByExampleSelective(@Param("example") YoungPermissionExample example, @Param("selective") YoungPermission.Column ... selective);

    List<YoungPermission> selectByExample(YoungPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungPermission.Column ... selective);

    YoungPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungPermission record, @Param("example") YoungPermissionExample example);

    int updateByExample(@Param("record") YoungPermission record, @Param("example") YoungPermissionExample example);

    int updateByPrimaryKeySelective(YoungPermission record);

    int updateByPrimaryKey(YoungPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}