package com.young.db.dao;

import com.young.db.entity.YoungBrand;
import com.young.db.entity.YoungBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungBrandMapper {
    long countByExample(YoungBrandExample example);

    int deleteByExample(YoungBrandExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungBrand record);

    int insertSelective(YoungBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungBrand selectOneByExample(YoungBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungBrand selectOneByExampleSelective(@Param("example") YoungBrandExample example, @Param("selective") YoungBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungBrand> selectByExampleSelective(@Param("example") YoungBrandExample example, @Param("selective") YoungBrand.Column ... selective);

    List<YoungBrand> selectByExample(YoungBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungBrand.Column ... selective);

    YoungBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungBrand record, @Param("example") YoungBrandExample example);

    int updateByExample(@Param("record") YoungBrand record, @Param("example") YoungBrandExample example);

    int updateByPrimaryKeySelective(YoungBrand record);

    int updateByPrimaryKey(YoungBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}