package com.young.db.dao;

import com.young.db.entity.YoungFootprint;
import com.young.db.entity.YoungFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungFootprintMapper {
    long countByExample(YoungFootprintExample example);

    int deleteByExample(YoungFootprintExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungFootprint record);

    int insertSelective(YoungFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungFootprint selectOneByExample(YoungFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungFootprint selectOneByExampleSelective(@Param("example") YoungFootprintExample example, @Param("selective") YoungFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungFootprint> selectByExampleSelective(@Param("example") YoungFootprintExample example, @Param("selective") YoungFootprint.Column ... selective);

    List<YoungFootprint> selectByExample(YoungFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungFootprint.Column ... selective);

    YoungFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungFootprint record, @Param("example") YoungFootprintExample example);

    int updateByExample(@Param("record") YoungFootprint record, @Param("example") YoungFootprintExample example);

    int updateByPrimaryKeySelective(YoungFootprint record);

    int updateByPrimaryKey(YoungFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}