package com.young.db.dao;

import com.young.db.entity.YoungAddress;
import com.young.db.entity.YoungAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungAddressMapper {
    long countByExample(YoungAddressExample example);

    int deleteByExample(YoungAddressExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungAddress record);

    int insertSelective(YoungAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAddress selectOneByExample(YoungAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAddress selectOneByExampleSelective(@Param("example") YoungAddressExample example, @Param("selective") YoungAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungAddress> selectByExampleSelective(@Param("example") YoungAddressExample example, @Param("selective") YoungAddress.Column ... selective);

    List<YoungAddress> selectByExample(YoungAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungAddress.Column ... selective);

    YoungAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungAddress record, @Param("example") YoungAddressExample example);

    int updateByExample(@Param("record") YoungAddress record, @Param("example") YoungAddressExample example);

    int updateByPrimaryKeySelective(YoungAddress record);

    int updateByPrimaryKey(YoungAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}