package com.young.db.dao;

import com.young.db.entity.YoungGroupon;
import com.young.db.entity.YoungGrouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YoungGrouponMapper {
    long countByExample(YoungGrouponExample example);

    int deleteByExample(YoungGrouponExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(YoungGroupon record);

    int insertSelective(YoungGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGroupon selectOneByExample(YoungGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGroupon selectOneByExampleSelective(@Param("example") YoungGrouponExample example, @Param("selective") YoungGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YoungGroupon> selectByExampleSelective(@Param("example") YoungGrouponExample example, @Param("selective") YoungGroupon.Column ... selective);

    List<YoungGroupon> selectByExample(YoungGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YoungGroupon.Column ... selective);

    YoungGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YoungGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") YoungGroupon record, @Param("example") YoungGrouponExample example);

    int updateByExample(@Param("record") YoungGroupon record, @Param("example") YoungGrouponExample example);

    int updateByPrimaryKeySelective(YoungGroupon record);

    int updateByPrimaryKey(YoungGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") YoungGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table young_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}